<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.inqwise.indexer</groupId>
	<artifactId>inqwise-indexer</artifactId>
	<version>0.1.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>inqwise-indexer</name>

	<modules>
		<module>indexer-dependencies</module>
		<module>indexer-parent</module>
		<module>indexer-core</module>
		<module>indexer-events</module>
		<module>indexer-coordination</module>
		<module>indexer-query</module>
		<module>indexer-query-rest</module>
		<module>indexer</module>
		<module>indexer-example-hacker-news-model</module>
		<module>indexer-example-hacker-news-actions</module>
		<module>indexer-example-hacker-news-reports</module>
		<module>indexer-web</module>
		<module>indexer-node-application</module>
		<module>indexer-example-hacker-news</module>
		<module>indexer-load</module>
	</modules>
</project>
