<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.inqwise.indexer</groupId>
		<artifactId>indexer-parent</artifactId>
		<version>0.1.0-SNAPSHOT</version>
		<relativePath>../indexer-parent/pom.xml</relativePath>
	</parent>

	<artifactId>indexer-example-hacker-news-node-application</artifactId>
	<name>inqwise-indexer-example-hacker-news-node-application</name>

	<dependencies>
		<dependency>
			<groupId>com.inqwise.indexer</groupId>
			<artifactId>indexer-node-application</artifactId>
		</dependency>
		<dependency>
			<groupId>com.inqwise.indexer</groupId>
			<artifactId>indexer-example-hacker-news</artifactId>
		</dependency>
		<dependency>
			<groupId>com.inqwise.indexer</groupId>
			<artifactId>indexer-example-hacker-news-actions</artifactId>
		</dependency>
		<dependency>
			<groupId>com.inqwise.indexer</groupId>
			<artifactId>indexer-example-hacker-news-reports</artifactId>
		</dependency>
		<dependency>
			<groupId>io.vertx</groupId>
			<artifactId>vertx-launcher-application</artifactId>
		</dependency>
		<dependency>
			<groupId>io.vertx</groupId>
			<artifactId>vertx-hazelcast</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.vertx</groupId>
			<artifactId>vertx-junit5</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<finalName>inqwise-hacker-news-indexer-node</finalName>
		<plugins>
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<configuration>
					<from>
						<image>eclipse-temurin:21-jre-alpine@sha256:3f08b13888f595cc49edabea7250ba69499ba25602b267da591720769400e08c</image>
						<platforms>
							<platform>
								<architecture>${jib.platform.architecture}</architecture>
								<os>linux</os>
							</platform>
						</platforms>
					</from>
					<to>
						<image>inqwise/indexer-node-hacker-news:${project.version}</image>
					</to>
					<container>
						<mainClass>io.vertx.launcher.application.VertxApplication</mainClass>
						<args>
							<arg>com.inqwise.indexer.example.hn.node.application.HackerNewsIndexerNodeApplicationVerticle</arg>
							<arg>--options</arg>
							<arg>/config/vertx-options.json</arg>
							<arg>--conf</arg>
							<arg>/config/indexer-node.json</arg>
						</args>
						<ports>
							<port>3000</port>
							<port>5701</port>
							<port>8080</port>
							<port>8081</port>
							<port>8083</port>
							<port>8084</port>
							<port>8086</port>
							<port>9090</port>
							<port>15701</port>
						</ports>
						<user>10001:10001</user>
					</container>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.6.1</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<createDependencyReducedPom>false</createDependencyReducedPom>
							<filters>
								<filter>
									<artifact>*:*</artifact>
									<excludes>
										<exclude>META-INF/*.SF</exclude>
										<exclude>META-INF/*.DSA</exclude>
										<exclude>META-INF/*.RSA</exclude>
										<exclude>module-info.class</exclude>
										<exclude>META-INF/versions/*/module-info.class</exclude>
									</excludes>
								</filter>
							</filters>
							<transformers>
								<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
								<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
									<resource>META-INF/io.netty.versions.properties</resource>
								</transformer>
								<transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
									<mainClass>io.vertx.launcher.application.VertxApplication</mainClass>
								</transformer>
							</transformers>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
