apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: inqwise-indexer

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - service-headless.yaml

configMapGenerator:
  - name: indexer-cluster-config
    files:
      - hazelcast.xml=config/hazelcast.xml
      - vertx-options.json=config/vertx-options.json

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: inqwise-indexer
      app.kubernetes.io/part-of: inqwise-indexer
