apiVersion: v1
kind: Service
metadata:
  name: indexer-node
spec:
  selector:
    app.kubernetes.io/name: inqwise-indexer
    app.kubernetes.io/component: node
  ports:
    - name: console
      port: 3000
      targetPort: console
    - name: admin
      port: 8080
      targetPort: admin
    - name: actions
      port: 8081
      targetPort: actions
    - name: runtime
      port: 8083
      targetPort: runtime
    - name: health
      port: 8084
      targetPort: health
    - name: reports
      port: 8086
      targetPort: reports
    - name: metrics
      port: 9090
      targetPort: metrics
