package com.inqwise.indexer.load.api;

public enum IndexerLoadState {
	CREATED,
	STARTING,
	HISTORICAL_LOADING,
	HISTORICAL_COMPLETE,
	CATCH_UP_BARRIER_REQUESTED,
	CATCH_UP_READY,
	WAITING_FOR_REVIEW,
	APPROVED,
	PUBLISHED,
	FAILED,
	CANCELLED
}
