package com.inqwise.indexer;

public enum IndexerEventType {
	INDEXER_STARTED,
	INDEXER_STOPPED,
	ACTION_ITEM_RECEIVED,
	CONSUMER_PAUSED,
	ACTION_ITEM_PROCESSING_STARTED,
	ACTION_ITEM_PROCESSING_COMPLETED,
	ACTION_ITEM_COMMITTED,
	ACTION_STREAM_COMPLETED,
	CONSUMER_RESUMED,
	ACTION_ITEM_FAILED
}
