<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.inqwise.indexer</groupId>
	<artifactId>indexer-dependencies</artifactId>
	<version>0.1.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>inqwise-indexer-dependencies</name>

	<properties>
		<vertx.version>5.1.1</vertx.version>
		<junit.version>5.10.2</junit.version>
		<inqwise.errors.version>2.1.1</inqwise.errors.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.vertx</groupId>
				<artifactId>vertx-stack-depchain</artifactId>
				<version>${vertx.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.inqwise</groupId>
				<artifactId>inqwise-errors</artifactId>
				<version>${inqwise.errors.version}</version>
			</dependency>
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter</artifactId>
				<version>${junit.version}</version>
			</dependency>
			<dependency>
				<groupId>com.inqwise.indexer</groupId>
				<artifactId>indexer-core</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.inqwise.indexer</groupId>
				<artifactId>indexer-events</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.inqwise.indexer</groupId>
				<artifactId>indexer-coordination</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.inqwise.indexer</groupId>
				<artifactId>indexer</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>
